# Generated by Django 5.1.2 on 2024-10-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_testcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
