# Generated by Django 5.1.2 on 2024-11-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_testcase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("FUNCTIONAL", "Functional"),
                    ("NON_FUNCTIONAL", "Non-Functional"),
                    ("SECURITY", "Security"),
                    ("PERFORMANCE", "Performance"),
                ],
                default="FUNCTIONAL",
                max_length=20,
            ),
        ),
    ]
